// <auto-generated />
namespace MonthlyBudget.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tryingtopushtogithub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryingtopushtogithub));
        
        string IMigrationMetadata.Id
        {
            get { return "202105070055144_trying to push to github"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
